api_platform:
    title: Baron property service
    version: 1.0.1
    show_webby: false
    graphql:
        graphql_playground:
            enabled: true
    patch_formats:
        json: ['application/merge-patch+json']
    name_converter: 'Symfony\Component\Serializer\NameConverter\CamelCaseToSnakeCaseNameConverter'
    swagger:
        versions: [3]
    defaults:
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
        normalization_context:
            skip_null_values: true
