version: '3'

networks:
  web:
    external: true
  internal:
    external: false

services:
  app:
    build: .
    restart: unless-stopped
    labels:
      - "traefik.http.routers.baron-rtw-insecure.rule=Host(`woningen.uwbaron.nl`)"
      - "traefik.http.routers.baron-rtw-insecure.middlewares=https-only@file"
      - "traefik.http.routers.baron-rtw.rule=Host(`woningen.uwbaron.nl`)"
      - "traefik.http.routers.baron-rtw.tls=true"
      - "traefik.http.routers.baron-rtw.tls.certresolver=le"
      - "traefik.http.routers.baron-rtw.middlewares=security-headers@file"
      - "traefik.http.services.baron-rtw.loadbalancer.server.port=80"
      - "traefik.http.middlewares.test-passtlsclientcert.passtlsclientcert.pem=true"
    networks:
      - web
      - internal
    volumes:
      - ./.env.local.php:/var/www/.env.local.php
    depends_on:
      - db

  db:
    image: mariadb:10.3.31-focal
    restart: unless-stopped
    networks:
      - internal
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: db
      MYSQL_USER: db
      MYSQL_PASSWORD: password
    labels:
      - "traefik.enable=false"
    volumes:
      - /opt/baron_mysql:/var/lib/mysql