#!/bin/bash

## Description: Setup init login
## Usage: init
## Example: "ddev init"

echo "Running init script on the host system."
date
echo "Start script"

ddev composer install
make reset-db

date
echo "End script"
