name: baron-property-service
type: php
docroot: public
php_version: "8.1"
webserver_type: nginx-fpm
router_http_port: "80"
router_https_port: "443"
xdebug_enabled: false
additional_hostnames: []
additional_fqdns: []
mariadb_version: "10.3"
mysql_version: ""
project_tld: nl.local
nfs_mount_enabled: false
mutagen_enabled: false
use_dns_when_possible: true
timezone: Europe/Amsterdam
composer_version: ""
disable_settings_management: true
web_environment: []
