name: Deploy application

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: SCP files
        uses: appleboy/scp-action@master
        with:
          host: woningen.uwbaron.nl
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: 22
          source: "${{ github.sha }}-release.tar.gz"
          target: "/home/${{ secrets.USERNAME }}/releases/tars/"

      - name: SSH actions
        uses: appleboy/ssh-action@master
        with:
          host: woningen.uwbaron.nl
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: 22
          script: |
            "/home/${{ secrets.USERNAME }}/go-deploy unpack -f /home/${{ secrets.USERNAME }}/releases/tars/${{ github.sha }}-release.tar.gz"
            "/home/${{ secrets.USERNAME }}/go-deploy symlink -r $CI_PIPELINE_ID-release"
            "rm -rf \`ls -v -d -1 /home/${{ secrets.USERNAME }}/releases/** | grep -w release | head -n -5\`"
            "rm /home/${{ secrets.USERNAME }}/releases/tars/*"
            "sudo service php8.1-fpm reload"

